In [24]:
import numpy as np

vc=[1,2,39,0,8]
vb=[1,2,38,0,8]

avg_vc=np.mean(vc)
avg_vb=np.mean(vb)

mul=np.multiply((vc-avg_vc),(vb-avg_vb))

In [25]:
np.mean(mul)/(np.std(vb)*np.std(vc))

0.999986231330961

In [16]:
#corrcoef得到相关系数矩阵（向量的相似程度）
np.corrcoef(vc,vb)

array([[1.        , 0.99998623],
       [0.99998623, 1.        ]])

In [5]:
import numpy as np

Mat1 = np.array([[1, 2, 3], [4, 5, 6]])
Mat2 = np.array([[11, 25, 346], [734, 48, 49]])

print("矩阵1=\n", Mat1)
print("矩阵2=\n", Mat2)

矩阵1=
 [[1 2 3]
 [4 5 6]]
矩阵2=
 [[ 11  25 346]
 [734  48  49]]


In [6]:
np.corrcoef(Mat1, Mat2)

array([[ 1.        ,  1.        ,  0.88390399, -0.86539304],
       [ 1.        ,  1.        ,  0.88390399, -0.86539304],
       [ 0.88390399,  0.88390399,  1.        , -0.53057867],
       [-0.86539304, -0.86539304, -0.53057867,  1.        ]])