In [39]:
import numpy as np

X = np.array([[ 1, -1,  2],
                [ 2,  0,  0],
                [ 0,  1, -1]])

# z-scores

零-均值规范化也称标准差标准化，经过处理的数据的均值为0，标准差为1.

$(X-mean)/std$ 

```
X.mean(axis=0)

array([1.        , 0.        , 0.33333333])

X.std(axis=0)

array([0.81649658, 0.81649658, 1.24721913])
```

In [40]:
(X-X.mean(axis=0))/X.std(axis=0)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

# sklearn.preprocessing.scale

In [41]:
from sklearn import preprocessing

X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

处理后数据的均值和方差:

In [42]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [43]:
X_scaled.std(axis=0)

array([1., 1., 1.])

其中,axis=0表示纵向，axis=1表示横向。

此时，均值为0，方差为1.

# sklearn.preprocessing.StandardScaler

In [53]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X)

In [49]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [57]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [50]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [54]:
scaler.var_

array([0.66666667, 0.66666667, 1.55555556])

In [58]:
scaler.n_samples_seen_

3

In [60]:
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [61]:
scaler.transform([[-1,  1, 0]]) 

array([[-2.44948974,  1.22474487, -0.26726124]])